coding-for-fun-org/frontend

- .github/pull_request_template.md
- README.md
- update readme
- update pull request template title for note
> chore: update readme to help setting up github env variables

- src/server/auth.ts
- src/types/environment.d.ts
> chore: add missing code

- .eslintrc.cjs
- .github/workflows/can-pr-merge.yaml
- .prettierrc
- jest.config.cjs
- jest.polyfills.js
- jest.setup.ts
- package-lock.json
- package.json
- src/__mocks__/file.ts
- src/__mocks__/style.ts
- src/modules/github/components/SignButton.test.tsx
- src/utils/test/msw/handlers.ts
- src/utils/test/msw/server.ts
- src/utils/test/testing-library.tsx
- tsconfig.json
- Install Jest so we can write a test code
> chore: install jest

- package-lock.json
- package.json
- src/app/[lang]/(client)/github/page.tsx
- src/app/[lang]/(client)/layout.tsx
- src/app/[lang]/layout.tsx
- src/components/link-github-icon-button/link-github-icon-button.tsx
- src/components/toggle-theme-icon-button/toggle-theme-icon-button.tsx
- src/contexts/theme-provider.tsx
- src/dictionaries/en.json
- src/elements/alert-dialog/_alert-dialog.tsx
- src/elements/alert-dialog/alert-dialog.tsx
- src/elements/button/button.tsx
- src/elements/checkbox/checkbox.tsx
- src/elements/collapsible/collapsible.tsx
- src/elements/label/label.tsx
- src/elements/progress/progress.tsx
- src/elements/textarea/textarea.tsx
- src/elements/toast/toast.tsx
- src/elements/tooltip/tooltip.tsx
- src/styles/index.scss
- src/styles/parts/_button.scss
- src/styles/parts/_toast.scss
- src/types/index.ts
- src/utils/index.ts
- tailwind.config.ts
[issue-31](https://github.com/kafelix496/coding-for-fun/issues/31)
[issue-32](https://github.com/kafelix496/coding-for-fun/issues/32)
> feat(issue-31/32): create a elements and retain the theme

- src/elements/alert/_alert.tsx
- src/elements/alert/alert.tsx
- src/elements/toast/toast.tsx
- src/styles/index.scss
- src/styles/parts/_alert.scss
[issue-40](https://github.com/kafelix496/coding-for-fun/issues/40)
> feat(issue-40): add alert element

- src/modules/github/components/pull-review-form/pull-review-form.tsx
- src/modules/github/components/pull-review-form/utils.test.ts
- src/modules/github/components/pull-review-form/utils.ts
[issue-28](https://github.com/kafelix496/coding-for-fun/issues/28)
-
> feat(issue-28): write a test code and split the code

- src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
- src/modules/github/components/pull-review-form/pull-review-form.tsx
[issue-38](https://github.com/kafelix496/coding-for-fun/issues/38)
-
> feat(issue-38): use customized elements

- src/elements/alert-dialog/alert-dialog.tsx
[issue-39](https://github.com/kafelix496/coding-for-fun/issues/39)
> fix(issue-39): handle elements component

- src/modules/github/components/bulk-merge-prs/bulk-merge-prs.tsx
- src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
- src/modules/github/components/pull-review-form/pull-review-form.tsx
[issue-59](https://github.com/kafelix496/coding-for-fun/issues/59)
> feat(issue-59): make a space

- src/app/(views)/github/bulk-reviews/page.tsx
- src/app/(views)/layout.tsx
- src/dictionaries/en.ts
- src/elements/tabs/tabs.tsx
- src/modules/github/components/bulk-merge-prs/bulk-merge-prs.tsx
- src/modules/github/components/pull-review-form/pull-review-form.tsx
- src/modules/github/hooks/use-prs-group.ts
[issue-58](https://github.com/kafelix496/coding-for-fun/issues/58)
> feat(issue-58): display skeleton

- next.config.js
- package-lock.json
- package.json
- src/app/(views)/callback/auth/[provider]/application-install/page.tsx
- src/app/(views)/callback/auth/[provider]/authorize/page.tsx
- src/app/(views)/github/page.tsx
- src/app/(views)/page.tsx
- src/dictionaries/en.ts
- src/elements/avatar/avatar.tsx
- src/elements/tabs/tabs.tsx
- src/modules/github/components/connections/connections.tsx
- src/modules/github/components/index-tabs/index-tabs.tsx
- src/modules/github/components/new-connection-button/new-connection-button.tsx
- src/modules/github/components/pull-review-form/pull-review-form.tsx
- src/modules/github/hooks/use-installations.ts
- src/modules/github/hooks/use-pulls-group.ts
- src/modules/github/types/index.ts
- src/modules/github/types/server.ts
- src/services/github.ts
- src/services/url.ts
- tsconfig.json
[issue-67](https://github.com/kafelix496/coding-for-fun/issues/67)
> feat(issue-67): connection tab

- .github/workflows/can-merge-pull-request.yml
- .github/workflows/coverage-reports.yml
- coverage is not running when the pull request is merged into the main branch.
> chore: update github workflow

- .github/workflows/coverage-reports.yml
- codecov.yml
- src/components/link-github-icon-button/link-github-icon-button.tsx
- src/components/toggle-theme-icon-button/toggle-theme-icon-button.tsx
- src/elements/alert-dialog/alert-dialog.tsx
- src/elements/alert/alert.tsx
- src/elements/avatar/avatar.tsx
- src/elements/button/button.tsx
- src/elements/tabs/tabs.tsx
- src/elements/tooltip/tooltip.tsx
[issue-92](https://github.com/kafelix496/coding-for-fun/issues/92)
> bug(issue-92): hydration error

- src/dictionaries/en.ts
- src/modules/github/components/pull-review-form/pull-review-form.tsx
[issue-97](https://github.com/kafelix496/coding-for-fun/issues/97)
- add Submit button in en.ts
> feat(issue-97): use translate that code

- .gitmodules
- src/app/api/auth/access_token/[provider]/github.ts
- src/app/api/auth/access_token/[provider]/route.ts
- src/app/api/auth/csrf/route.ts
- src/app/api/auth/refresh_token/[provider]/github.ts
- src/app/api/auth/refresh_token/[provider]/route.ts
- src/app/api/auth/sign_in/github/route.ts
- src/app/api/auth/sign_out/github/route.ts
- src/app/api/github/app/installations/[installationId]/route.ts
- src/app/api/github/repos/[owner]/[repo]/pulls/[pullNumber]/reviews/route.ts
- src/app/api/github/repos/[owner]/[repo]/pulls/route.ts
- src/app/api/github/user/installations/[installationId]/repositories/route.ts
- src/app/api/github/user/installations/route.ts
- src/app/api/github/user/route.ts
- I don't care that backend code is exposed.
> chore: remove git module

- src/modules/github/components/pull-review-form/pull-review-form.tsx
- src/modules/github/components/pull-review-form/utils.test.ts
- src/modules/github/components/pull-review-form/utils.ts
[issue-50](https://github.com/kafelix496/coding-for-fun/issues/50)
- We can't find getuser. please add.
- We need to apply also request button, right? (I already applied)
> bug(issue-50): approve button should not be activated if one of pull request is created by himself

- package-lock.json
- package.json
- src/elements/alert-dialog/alert-dialog.tsx
- src/elements/dialog/dialog.test.tsx
- src/elements/dialog/dialog.tsx
[issue-113](https://github.com/kafelix496/coding-for-fun/issues/113)
> feat(issue-113): add dialog element

- package-lock.json
- package.json
- src/contexts/client-provider/client-provider.tsx
- src/dictionaries/en.ts
- src/elements/alert-dialog/alert-dialog.test.tsx
- src/elements/alert-dialog/alert-dialog.tsx
- src/elements/button/button.tsx
- src/elements/dialog/dialog.test.tsx
- src/elements/toast/toast.tsx
- src/modules/github/components/bulk-pull-reviews/bulk-pull-reviews.tsx
- src/modules/github/components/pull-review-form/hooks.ts
- src/modules/github/components/pull-review-form/pull-review-form.tsx
- src/modules/github/components/pull-review-form/types.ts
- src/modules/github/components/pull-review-form/utils.ts
- src/modules/github/hooks/use-current-user.ts
- src/modules/github/hooks/use-installations.ts
- src/modules/github/hooks/use-pulls-group.ts
- src/styles/parts/_toast.scss
- src/types/index.ts
- src/utils/index.ts
[issue-108](https://github.com/kafelix496/coding-for-fun/issues/108)
> feat(issue-108): react query

- src/dictionaries/en.ts
- src/elements/alert-dialog/alert-dialog.tsx
- src/modules/github/components/pull-review-form/pull-review-form.tsx
[issue-117](https://github.com/kafelix496/coding-for-fun/issues/117)
> feat(issue-117): add errorProps for alert dialog

- src/modules/github/components/connections/connections.tsx
- src/modules/github/hooks/use-installations.ts
- src/modules/github/hooks/use-pulls-group.ts
- src/utils/index.ts
[issue-115](https://github.com/kafelix496/coding-for-fun/issues/115)
> feat(issue-115): replace code using react-query

- src/modules/github/components/bulk-pull-reviews/bulk-pull-reviews.tsx
- src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
- src/modules/github/hooks/use-pulls-group.ts
- src/modules/github/types/index.ts
[issue-84](https://github.com/kafelix496/coding-for-fun/issues/84)
-
> feat(issue-84): add link to repository feature

- src/dictionaries/en.ts
- src/modules/github/components/connections/connections.tsx
- src/modules/github/hooks/use-installations.ts
[issue-69](https://github.com/kafelix496/coding-for-fun/issues/69)
- I think I can't know success and fail. I think only know in use-installation.ts, Is it possible?
> feat(issue-69): show alert dialog before deleting connection

- src/app/api/auth/refresh_token/[provider]/github.ts
- src/app/api/auth/refresh_token/[provider]/route.ts
- src/contexts/client-provider/client-provider.tsx
- src/modules/github/components/bulk-pull-reviews/bulk-pull-reviews.tsx
- src/modules/github/components/bulk-pull-reviews/queries.ts
- src/modules/github/queries/use-installations.ts
- src/modules/github/utils/axios.ts
This has a problem but it works pretty well.
-> refresh token will be canceled with signal
> chore: handle 401 error

- src/elements/dialog/dialog.tsx
- src/styles/index.scss
- src/styles/parts/_typography.scss
- update dialog style
- update markdown typography style
> chore: update dialog style and markdown typography style

- src/app/(views)/page.tsx
- src/modules/github/components/pull-list-item/pull-list-item.tsx
[issue-155](https://github.com/kafelix496/coding-for-fun/issues/155)
- also fixed the localStore undefined error
> bug(issue-155): do not shrink icon size

- src/modules/github/components/bulk-pull-reviews/hooks.ts
- src/modules/github/components/pull-list-by-repo/hooks.ts
- src/modules/github/components/pull-list-item-status/hooks.ts
- src/modules/github/components/pull-list-item-status/pull-list-item-status.tsx
- src/modules/github/components/pull-list-item-status/types.ts
- src/modules/github/components/pull-list-item-status/utils.test.ts
- src/modules/github/components/pull-list-item-status/utils.ts
- src/modules/github/components/pull-list-item/pull-list-item.tsx
- src/services/github.ts
- src/utils/index.ts
[issue-154](https://github.com/kafelix496/coding-for-fun/issues/154)
- split code and write test code
> bug(issue-154): cancel check run request when the component is destroyed

- src/dictionaries/en.ts
- src/elements/tooltip/tooltip.test.tsx
- src/elements/tooltip/tooltip.tsx
- src/modules/github/components/pull-list-item-status/hooks.ts
- src/modules/github/components/pull-list-item-status/pull-list-item-status.tsx
- src/modules/github/components/pull-list-item-status/utils.ts
- src/utils/test/testing-library.tsx
[issue-157](https://github.com/kafelix496/coding-for-fun/issues/157)
> feat(issue-157): show check status

- package-lock.json
- package.json
- src/components/link-github-icon-button/link-github-icon-button.tsx
- src/components/toggle-theme-icon-button/toggle-theme-icon-button.tsx
- src/elements/alert/alert.tsx
- src/elements/checkbox/checkbox.tsx
- src/elements/dialog/dialog.tsx
- src/elements/dropdown-menu/dropdown-menu.tsx
- src/elements/toast/toast.tsx
- src/modules/github/components/connections/connections.tsx
- src/modules/github/components/pull-list-by-repo/pull-list-by-repo.tsx
- src/modules/github/components/pull-list-item-status/pull-list-item-status.tsx
- src/modules/github/components/sign-in-button/sign-in-button.tsx
[issue-180](https://github.com/kafelix496/coding-for-fun/issues/180)
-
> feat(issue-180): Change icons from @radix-ui/react-icons to lucide-react

- package-lock.json
- package.json
- src/dictionaries/en.ts
- src/elements/dialog/dialog.tsx
- src/modules/github/components/pull-list-item/pull-list-item.tsx
- src/modules/github/contexts/selected-pulls-provider.tsx
- src/modules/github/types/index.ts
[issue-153](https://github.com/kafelix496/coding-for-fun/issues/153)
-
> feat(issue-153): Open dialog instead of link from pull request

- src/dictionaries/en.ts
- src/elements/radio-group/radio-group.tsx
- src/modules/github/components/bulk-pull-reviews/bulk-pull-reviews.tsx
[issue-200](https://github.com/kafelix496/coding-for-fun/issues/200)
-
> feat(issue-200): modify location of expand all button feature

- src/modules/github/components/pull-list-item-status/pull-list-item-status.tsx
[issue-212](https://github.com/kafelix496/coding-for-fun/issues/212)
-
> feat(issue-212): Yellow icons are too small after switching to Lucid icons

- src/modules/github/contexts/selected-pulls-provider.tsx
[issue-211](https://github.com/kafelix496/coding-for-fun/issues/211)
> bug(issue-211): retain open status

- src/utils/index.test.ts
- src/utils/index.ts
isObjectLike, isPlainObject and isString
> fix: add util functions

- src/app/(views)/github/t/@pullButtons/pulls/page.tsx
- src/app/(views)/github/t/layout.tsx
- src/app/(views)/github/t/pulls/page.tsx
- src/elements/tabs/tabs.tsx
- src/modules/github/components/bulk-pull-reviews/bulk-pull-reviews.tsx
[issue-322](https://github.com/kafelix496/coding-for-fun/issues/322)
-
> feat(issue-322): Make the page tab and the action buttons same line

- src/app/(views)/github/t/@pullButtons/pulls/page.tsx
[issue-344](https://github.com/kafelix496/coding-for-fun/issues/344)
-
> feat(issue-344): work only when there are repos

- src/modules/github/components/pull-list-item-status/pull-list-item-status.test.tsx
- src/modules/github/components/pull-list-item-status/pull-list-item-status.tsx
[issue-215](https://github.com/kafelix496/coding-for-fun/issues/215)
-
> feat(issue-215): Make a test of `pull-list-item-status.tsx`

- src/contexts/client-provider/client-provider.tsx
https://linear.app/coding-for-fun/issue/RFF-14/change-tanstackquery-options
-
> chore(rff-14): change tanstackquery-options

- src/app/(views)/github/t/merge/page.tsx
- src/elements/stepper/stepper.tsx
[rff-19](https://linear.app/coding-for-fun/issue/RFF-19/create-a-stepper)
-
> feat(rff-19): creating a stepper
